@startuml wakuwaku
title 工科展でのビューワ

participant システム
actor ユーザ
actor 同伴者

== タイトルシーン ==
システム -> ユーザ : タイトル画面表示
ユーザ -> システム : スタートボタンを押す

== シナリオシーン ==
システム -> ユーザ : シナリオの再生（一方的）
ユーザ -> システム : ボタンを押す

== 経路選択シーン ==
システム -> ユーザ : 3つの経路を表示
システム -> ユーザ : システム音声案内\nどの経路で避難するか選んでね
ユーザ -> システム : それぞれの経路を確認\n（ボタンを押す）

alt 最短経路
    システム -> ユーザ : システム音声案内\n最短経路で避難所に到達するよ
else 道路の幅を考慮した経路
    システム -> ユーザ : システム音声案内\n細い道を避けて避難所に到達するよ
else 倒壊度を考慮した経路
    システム -> ユーザ : システム音声案内\n倒れやすい建物を避けて避難所に到達するよ
end

ユーザ -> 同伴者 : どの経路がいいか相談
同伴者 -> ユーザ : 意見
ユーザ -> システム : 経路を選択

== 避難シーン ==
システム -> ユーザ : 避難開始の合図，選択した経路とタイマー表示
ユーザ -> システム : スティック操作
システム -> ユーザ : キャラクター移動

alt キャラクターが動けなくなった場合
    ユーザ -> システム : 四角ボタンを押す
    システム -> ユーザ : スタートの位置に戻る
else 選択した経路が通行不可能だった場合
    ユーザ -> 同伴者 : 経路変更の相談
    同伴者 -> ユーザ : 意見
    ユーザ -> システム : 違う道で避難所に向かう
end

alt 時間内に避難所に到達
    システム -> ユーザ : 避難成功
else 時間切れ
    システム -> ユーザ : 避難失敗
end

== リザルトシーン ==
alt 避難成功
    alt 36秒以内に成功
        システム -> ユーザ : 評価S
    else 1分12秒以内に成功
        システム -> ユーザ : 評価A
    else 1分48秒以内に成功
        システム -> ユーザ : 評価B
    else 2分24秒以内に成功
        システム -> ユーザ : 評価C
    else 3分以内に成功
        システム -> ユーザ : 評価D
    end
    システム -> ユーザ : クリアタイム
    システム -> ユーザ : フィードバック
else 避難失敗
    システム -> ユーザ : 評価F
    システム -> ユーザ : フィードバック
end
システム -> ユーザ : 選択した経路と通った経路の差分

@enduml