@startuml wakuwaku
title ワクワクに向けてのビューワ

participant システム
actor ユーザ
actor 同伴者

== タイトルシーン ==
システム -> ユーザ : タイトル画面表示
ユーザ -> システム : スタートボタンを押す

== シナリオシーン ==
システム -> ユーザ : 導入の質問\n例：最近の震災を知っている？
ユーザ -> 同伴者 : 相談\n例：どんな地震起きてるかな？
同伴者 -> ユーザ : 意見\n例：OO地震
ユーザ -> システム : 回答する

alt わからない
    システム -> ユーザ : フィードバック
else OO地震
    システム -> ユーザ : フィードバック
end

システム -> ユーザ : シナリオ\n実際の被害と防災の重要性
システム -> ユーザ : 家庭内の防災状況の質問
ユーザ -> 同伴者 : 防災状況の確認
同伴者 -> ユーザ : 防災状況
ユーザ -> システム : 回答する

alt 何も対策していない
    システム -> ユーザ : フィードバック
else 対策している
    システム -> ユーザ : フィードバック
end

システム -> ユーザ : 質問\n例：今地震が起きたらどう避難する？
ユーザ -> 同伴者 : 避難方法の相談
同伴者 -> ユーザ : 避難場所，避難経路，etc...
ユーザ -> システム : 回答する

alt 具体的な回答
    システム -> ユーザ : フィードバック
else わからない
    システム -> ユーザ : フィードバック
end

システム -> ユーザ : 実際に経路を考えて避難しよう！！！
ユーザ -> システム : ボタンを押す

== 経路選択シーン ==
@enduml