@startuml wakuwaku
title ワクワクに向けてのビューワ

participant システム
actor 体験者
actor 同伴者

== タイトルシーン ==
システム -> 体験者 : タイトル画面表示
体験者 -> システム : スタートボタンを押す

== シナリオシーン ==
par 同時に働きかける
    システム [#red]-> 体験者 : <color : red>導入の質問\n<color : red>例：最近の震災を知っている？
    システム [#red]-> 同伴者
end
体験者 [#red]-> 同伴者 : <color : red>相談\n<color : red>例：どんな地震起きてるかな？
同伴者 [#red]-> 体験者 : <color : red>意見\n<color : red>例：OO地震
体験者 [#red]-> システム : <color : red>回答する

alt わからない
    システム [#red]-> 体験者 : <color : red>フィードバック
else OO地震
    システム [#red]-> 体験者 : <color : red>フィードバック
end

システム [#red]-> 体験者 : <color : red>実際の被害と防災の重要性

par 同時に働きかける
    システム [#red]-> 体験者 : <color : red>家庭内の防災状況の質問
    システム [#red]-> 同伴者
end
体験者 [#red]-> 同伴者 : <color : red>防災状況の確認
同伴者 [#red]-> 体験者 : <color : red>防災状況
体験者 [#red]-> システム : <color : red>回答する

alt 何も対策していない
    システム [#red]-> 体験者 : <color : red>フィードバック
else 対策している
    システム [#red]-> 体験者 : <color : red>フィードバック
end

システム[#red]-> 体験者 : <color : red>質問\n<color : red>例：今地震が起きたらどう避難する？
体験者 [#red]-> 同伴者 : <color : red>避難方法の相談
同伴者 [#red]-> 体験者 : <color : red>避難場所，避難経路，etc...
体験者 [#red]-> システム : <color : red>回答する

alt 具体的な回答
    システム [#red]-> 体験者 : <color : red>フィードバック
else わからない
    システム [#red]-> 体験者 : <color : red>フィードバック
end

システム [#red]-> 体験者 : <color : red>実際に経路を考えて避難しよう！！！
体験者 -> システム : ボタンを押す

== 経路選択シーン ==
システム -> 体験者 : 経路の表示
par 同時に働きかける
    システム [#red]-> 体験者: <color : red> 話し合わせる仕掛け
    システム [#red]-> 同伴者
end

体験者 <-> 同伴者 : 経路の確認，比較\n例：この経路はOOで危険だよね
体験者 -> システム : 経路の選択

== 避難シーン ==
システム -> 体験者 : 避難開始の合図，カウントダウン開始
体験者 -> システム : コントローラの操作
システム -> 体験者 : キャラクター移動

alt キャラクターが動けなくなった場合
    体験者 -> システム : 四角ボタンを押す
    システム -> 体験者 : スタートの位置に戻る
else 選択した経路が通行不可能だった場合
    par 同時に働きかける
        システム [#red]-> 体験者 : <color : red>話し合わせる仕掛け
        システム [#red]-> 同伴者
    end
    体験者 -> 同伴者 : 経路変更の相談
    同伴者 -> 体験者 : 意見
    体験者 -> システム : 違う道で避難所に向かう
end

alt 時間内に避難所に到達
    システム -> 体験者 : 避難成功
else 時間切れ
    システム -> 体験者 : 避難失敗
end

== リザルトシーン ==
alt 避難成功
    alt 36秒以内に成功
        システム -> 体験者 : 評価S
    else 1分12秒以内に成功
        システム -> 体験者 : 評価A
    else 1分48秒以内に成功
        システム -> 体験者 : 評価B
    else 2分24秒以内に成功
        システム -> 体験者 : 評価C
    else 3分以内に成功
        システム -> 体験者 : 評価D
    end
    システム -> 体験者 : クリアタイム
    システム -> 体験者 : フィードバック
else 避難失敗
    システム -> 体験者 : 評価F
    システム -> 体験者 : フィードバック
end

システム -> 体験者 : 選択した経路と通った経路の差分
par 同時に働きかける
    システム [#red]-> 体験者 : <color : red>話し合わせる仕掛け
    システム [#red]-> 同伴者
end

== 帰宅後 ==
体験者 <[#red]-> 同伴者 : <color : red>自分の家で地震が起きた際の対策

@enduml